
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/auladb
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: non_null
